JSON_COMMA = ","
JSON_COLON = ":"
JSON_LEFTBRACKET = "["
JSON_RIGHTBRACKET = "]"
JSON_LEFTBRACE = "{"
JSON_RIGHTBRACE = "}"
JSON_QUOTE = '"'

JSON_WHITESPACE = [" ", "\t", "\b", "\n", "\r"]
JSON_SYNTAX = [
    JSON_COMMA,
    JSON_COLON,
    JSON_LEFTBRACKET,
    JSON_RIGHTBRACKET,
    JSON_LEFTBRACE,
    JSON_RIGHTBRACE,
]
JSON_NUMERIC = [str(d) for d in range(0, 10)] + ["-", "e", "."]

JSON_FALSE = "false"
JSON_TRUE = "true"
JSON_NULL = "null"
JSON_INFINITY = "Infinity"
JSON_NINFINITY = "-Infinity"
JSON_NAN = "NaN"
JSON_CONST = [JSON_FALSE, JSON_TRUE, JSON_NULL, JSON_INFINITY, JSON_NINFINITY, JSON_NAN]
